export {default as Blog} from './blog/Blog'
export {default as Features} from './features/Features'
export {default as Header} from './header/Header'
export {default as Possiblity} from './possibility/possibility'
export {default as WhatGP3} from  './whatGP3/WhatGP3'
export {default as Footer} from './footer/Footer'